// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzRPRxxygdI6V6KVPmIsW_1jn8FgjMtxs',
    appId: '1:21386100371:web:f2a2126422374c5b3b1766',
    messagingSenderId: '21386100371',
    projectId: 'my-milkmate-app-1da38',
    authDomain: 'my-milkmate-app-1da38.firebaseapp.com',
    storageBucket: 'my-milkmate-app-1da38.firebasestorage.app',
    measurementId: 'G-FWLTHRRR6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZUJRPI0z5akjpmwbjJJlRLuD33H5gJv4',
    appId: '1:21386100371:android:b7be4dd84e47901c3b1766',
    messagingSenderId: '21386100371',
    projectId: 'my-milkmate-app-1da38',
    storageBucket: 'my-milkmate-app-1da38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByyT0b1up1GAEf0W6VuSeT-YVUAdCSYVc',
    appId: '1:21386100371:ios:111c21753d65e8e03b1766',
    messagingSenderId: '21386100371',
    projectId: 'my-milkmate-app-1da38',
    storageBucket: 'my-milkmate-app-1da38.firebasestorage.app',
    iosBundleId: 'com.example.milkmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByyT0b1up1GAEf0W6VuSeT-YVUAdCSYVc',
    appId: '1:21386100371:ios:111c21753d65e8e03b1766',
    messagingSenderId: '21386100371',
    projectId: 'my-milkmate-app-1da38',
    storageBucket: 'my-milkmate-app-1da38.firebasestorage.app',
    iosBundleId: 'com.example.milkmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzRPRxxygdI6V6KVPmIsW_1jn8FgjMtxs',
    appId: '1:21386100371:web:2c22d9b58f7dfede3b1766',
    messagingSenderId: '21386100371',
    projectId: 'my-milkmate-app-1da38',
    authDomain: 'my-milkmate-app-1da38.firebaseapp.com',
    storageBucket: 'my-milkmate-app-1da38.firebasestorage.app',
    measurementId: 'G-XGS4V7PPNK',
  );
}
